/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miinaharavav2;

/**
 *
 * @author Marko
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n11 = new javax.swing.JButton();
        n13 = new javax.swing.JButton();
        n14 = new javax.swing.JButton();
        n15 = new javax.swing.JButton();
        n16 = new javax.swing.JButton();
        n17 = new javax.swing.JButton();
        n18 = new javax.swing.JButton();
        n19 = new javax.swing.JButton();
        n21 = new javax.swing.JButton();
        n12 = new javax.swing.JButton();
        n23 = new javax.swing.JButton();
        n24 = new javax.swing.JButton();
        n25 = new javax.swing.JButton();
        n26 = new javax.swing.JButton();
        n27 = new javax.swing.JButton();
        n28 = new javax.swing.JButton();
        n29 = new javax.swing.JButton();
        n31 = new javax.swing.JButton();
        n22 = new javax.swing.JButton();
        n41 = new javax.swing.JButton();
        n51 = new javax.swing.JButton();
        n61 = new javax.swing.JButton();
        n71 = new javax.swing.JButton();
        n81 = new javax.swing.JButton();
        n91 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        valikkoRivi = new javax.swing.JMenuBar();
        valikko = new javax.swing.JMenu();
        uusiPeli = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sulje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        n11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n31.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n41.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n51.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n61.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n71.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n81.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        n91.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton37.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton39.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton40.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton41.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton42.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton43.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton44.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton45.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton46.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton47.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton48.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton49.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton50.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton51.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton52.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton53.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton54.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton55.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton56.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton57.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton58.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton59.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton60.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton61.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton62.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton63.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton64.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton65.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton66.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton67.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton68.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton69.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton70.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton71.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton72.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton73.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton74.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton75.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton76.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton77.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton78.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton79.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton80.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton81.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton82.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton83.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton84.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton85.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton86.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton87.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton88.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton89.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton90.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton91.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        jButton92.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marko\\Documents\\NetBeansProjects\\miinaharava\\build\\classes\\Miinaharava\\images\\suljettu.png")); // NOI18N

        valikko.setText("Peli");

        uusiPeli.setText("Uusi peli");
        valikko.add(uusiPeli);
        valikko.add(jSeparator1);

        sulje.setText("Sulje");
        sulje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suljeActionPerformed(evt);
            }
        });
        valikko.add(sulje);

        valikkoRivi.add(valikko);

        setJMenuBar(valikkoRivi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(n13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n41, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n51, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n61, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n71, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n81, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n91, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton67, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton73, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton74, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton75, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton76, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton77, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton81, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton82, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton83, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton85, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton86, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton87, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton88, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton89, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton90, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton91, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton92, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n91, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton85, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton86, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton87, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton88, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton89, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton90, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton91, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton92, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n81, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton77, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton78, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton79, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton80, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton81, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton82, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton83, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton84, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n71, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton73, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton74, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton75, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton76, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n61, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton67, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(n11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suljeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_suljeActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton n11;
    private javax.swing.JButton n12;
    private javax.swing.JButton n13;
    private javax.swing.JButton n14;
    private javax.swing.JButton n15;
    private javax.swing.JButton n16;
    private javax.swing.JButton n17;
    private javax.swing.JButton n18;
    private javax.swing.JButton n19;
    private javax.swing.JButton n21;
    private javax.swing.JButton n22;
    private javax.swing.JButton n23;
    private javax.swing.JButton n24;
    private javax.swing.JButton n25;
    private javax.swing.JButton n26;
    private javax.swing.JButton n27;
    private javax.swing.JButton n28;
    private javax.swing.JButton n29;
    private javax.swing.JButton n31;
    private javax.swing.JButton n41;
    private javax.swing.JButton n51;
    private javax.swing.JButton n61;
    private javax.swing.JButton n71;
    private javax.swing.JButton n81;
    private javax.swing.JButton n91;
    private javax.swing.JMenuItem sulje;
    private javax.swing.JMenuItem uusiPeli;
    private javax.swing.JMenu valikko;
    private javax.swing.JMenuBar valikkoRivi;
    // End of variables declaration//GEN-END:variables
}
